export const descriptions = [
    "Nestled in the heart of the Sierra Nevada Mountains, this campground offers breathtaking views, easy access to nearby hiking trails, and a variety of recreational opportunities. Whether you're into fishing, boating, or simply lounging by the fire pit, you'll find plenty to keep you entertained during your stay.",
    "Escape to the peaceful beauty of the Rocky Mountains at this stunning campground. Surrounded by rolling hills, lush forests, and sparkling streams, it's the perfect place to get away from it all.",
    "Discover the magic of the Adirondack Mountains at this peaceful campground. With a variety of sites to choose from, including RV hookups and tent camping, it's the perfect place to escape from the hustle and bustle of everyday life.",
    'Set among the rolling hills and lush forests of the Appalachian Mountains, this campground offers breathtaking views, easy access to nearby lakes, and a variety of recreational opportunities.',
    'Surrounded by the beauty of the Great Smoky Mountains, this campground offers easy access to nearby hiking trails, fishing opportunities, and a variety of recreational activities.',
    "Escape to the heart of the Blue Ridge Mountains at this beautiful campground. With a variety of sites to choose from, including RV hookups and tent camping, it's the perfect place to get away from it all.",
    'Nestled in the heart of the Ozark Mountains, this peaceful campground offers breathtaking views, easy access to nearby hiking trails, and a variety of recreational opportunities.',
    "Discover the beauty of the White Mountains at this stunning campground. With a variety of sites to choose from, including RV hookups and tent camping, it's the perfect place to escape from the hustle and bustle of everyday life.",
    'Set among the rolling hills and lush forests of the Green Mountains, this campground offers breathtaking views, easy access to nearby lakes, and a variety of recreational opportunities.',
    "Escape to the peaceful beauty of the Catskill Mountains at this beautiful campground. With a variety of sites to choose from, including RV hookups and tent camping, it's the perfect place to get away from it all.",
    'Surrounded by the stunning beauty of the Rocky Mountains, this campground offers easy access to nearby hiking trails, fishing opportunities, and a variety of recreational activities.',
    'Nestled in the heart of the Cascades Mountains, this peaceful campground offers breathtaking views, easy access to nearby lakes, and a variety of recreational opportunities.',
    "Discover the magic of the Berkshire Mountains at this stunning campground. With a variety of sites to choose from, including RV hookups and tent camping, it's the perfect place to escape from the hustle and bustle of everyday life.",
    'Set among the rolling hills and lush forests of the Olympic Mountains, this campground offers breathtaking views, easy access to nearby hiking trails, and a variety of recreational opportunities.',
    "Escape to the heart of the Teton Mountains at this beautiful campground. With a variety of sites to choose from, including RV hookups and tent camping, it's the perfect place to get away from it all.",
];
